# Generated by Django 3.2 on 2021-11-28 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurateur', '0002_alter_place_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Place',
        ),
    ]
