# Generated by Django 3.2 on 2021-11-28 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0040_auto_20211128_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'не обработан'), (1, 'обработан')], db_index=True, default=0, verbose_name='статус заказа'),
        ),
    ]
